
# SEO settings
title: Nova
description: "Personal Blog of Bolkars"
keywords: "Sabri, Bolkar, Jekyll, theme, free, download, SEO, blog, web"
url: http://blognova.com
baseurl: ""
# baseurl: null

google_analytics: 
repo:
disqus_shortname: ""

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Bolkars
  job      : Electronics Engineering Senior 
  bio      : "Designer with a penchant for the web and animation design, having also strong interest in philosophy as well as neuroscience, particularly the applied one, neural engineering ."
  thumb    : /images/author.jpg
  email    : sabribolkar@gmail.com
  url      : http://blognova.com
  github   : http://github.com/delamine
  twitter  : 
  facebook : 
  linkedin : 

# social settings
og_locale: "pt_BR"
twitter_card: ""
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
